#!/usr/bin/env python3
import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass

import optuna

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PARAMS_PATH = os.path.join(ROOT_DIR, "params.hpp")

REL_SCORE_RE = re.compile(r"Relative\s*Score\s*[:=]\s*([0-9.]+)", re.IGNORECASE)
REL_ALT_RE = re.compile(r"^\s*Relative\s*=\s*([0-9.]+)\s*$", re.IGNORECASE | re.MULTILINE)


@dataclass
class TrialParams:
    max_branch: int
    rollout_horizon: int
    self_random_eps: float
    time_limit_ms: float


def write_params(p: TrialParams) -> None:
    entry = "{max_branch}, {rollout_horizon}, {self_random_eps:.6f}, {time_limit_ms:.6f}".format(
        max_branch=p.max_branch,
        rollout_horizon=p.rollout_horizon,
        self_random_eps=p.self_random_eps,
        time_limit_ms=p.time_limit_ms,
    )
    entries = ",\n".join([f"  {{{entry}}}"] * 9)
    template = """#pragma once

// Auto-generated by optuna_tune.py

struct Params {{
  int max_branch;
  int rollout_horizon;
  double self_random_eps;
  double time_limit_ms;
}};

static constexpr Params PARAMS_BY_M[9] = {{
{entries}
}};

inline const Params& params_for_m(int m) {{
  if(m < 0) m = 0;
  if(m > 8) m = 8;
  return PARAMS_BY_M[m];
}}
"""
    content = template.format(entries=entries)
    with open(PARAMS_PATH, "w", encoding="utf-8") as f:
        f.write(content)


def run_pahcer(cmd: str, timeout_sec: int) -> float:
    proc = subprocess.run(
        cmd,
        cwd=ROOT_DIR,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=timeout_sec,
        text=True,
    )
    out = proc.stdout
    if proc.returncode != 0:
        print(out)
        raise RuntimeError(f"pahcer failed (exit={proc.returncode})")

    m = REL_SCORE_RE.search(out) or REL_ALT_RE.search(out)
    if not m:
        print(out)
        raise RuntimeError("Relative score not found in output")
    return float(m.group(1))


def objective(trial: optuna.Trial, pahcer_cmd: str, timeout_sec: int) -> float:
    params = TrialParams(
        max_branch=trial.suggest_int("max_branch", 12, 60),
        rollout_horizon=20,
        self_random_eps=trial.suggest_float("self_random_eps", 0.0, 0.35),
        time_limit_ms=5000.0,
    )
    write_params(params)
    score = run_pahcer(pahcer_cmd, timeout_sec)
    return score


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--trials", type=int, default=50)
    parser.add_argument("--timeout", type=int, default=600)
    parser.add_argument(
        "--pahcer-cmd",
        default="pahcer run --freeze-best-scores",
    )
    parser.add_argument("--storage", default="sqlite:///optuna/optuna.db")
    parser.add_argument("--study-name", default="ahc061")
    args = parser.parse_args()

    study = optuna.create_study(
        study_name=args.study_name,
        storage=args.storage,
        direction="maximize",
        load_if_exists=True,
    )

    study.optimize(
        lambda t: objective(t, args.pahcer_cmd, args.timeout),
        n_trials=args.trials,
    )

    best = study.best_trial
    print("Best score:", best.value)
    print("Best params:")
    for k, v in best.params.items():
        print(" ", k, v)

    best_params = TrialParams(
        max_branch=int(best.params["max_branch"]),
        rollout_horizon=20,
        self_random_eps=float(best.params["self_random_eps"]),
        time_limit_ms=5000.0,
    )
    write_params(best_params)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
