#!/usr/bin/env python3
import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass

import optuna

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PARAMS_PATH = os.path.join(ROOT_DIR, "params.hpp")

REL_SCORE_RE = re.compile(r"Relative\s*Score\s*[:=]\s*([0-9.]+)", re.IGNORECASE)
REL_ALT_RE = re.compile(r"^\s*Relative\s*=\s*([0-9.]+)\s*$", re.IGNORECASE | re.MULTILINE)


@dataclass
class TrialParams:
    beam_width: int
    max_depth: int
    max_branch: int
    time_limit_ms: float
    alpha: float
    beta: float
    gamma: float
    edge_own_bonus: float
    edge_reinforce_factor: float
    enemy_lv1_bonus: float
    empty_adj_penalty: float
    enemy_adj_penalty: float
    low_value_bonus: float
    move_enemy_adj_penalty: float
    move_empty_adj_penalty: float
    onevone_attack_bonus: float
    onevone_attack_lv1_bonus: float
    onevone_approach_bonus: float
    onevone_frontier_bonus: float


def write_params(p: TrialParams) -> None:
    entry = "{beam_width}, {max_depth}, {max_branch}, {time_limit_ms:.6f}, {alpha:.6f}, {beta:.6f}, {gamma:.6f}, {edge_own_bonus:.6f}, {edge_reinforce_factor:.6f}, {enemy_lv1_bonus:.6f}, {empty_adj_penalty:.6f}, {enemy_adj_penalty:.6f}, {low_value_bonus:.6f}, {move_enemy_adj_penalty:.6f}, {move_empty_adj_penalty:.6f}, {onevone_attack_bonus:.6f}, {onevone_attack_lv1_bonus:.6f}, {onevone_approach_bonus:.6f}, {onevone_frontier_bonus:.6f}".format(
        beam_width=p.beam_width,
        max_depth=p.max_depth,
        max_branch=p.max_branch,
        time_limit_ms=p.time_limit_ms,
        alpha=p.alpha,
        beta=p.beta,
        gamma=p.gamma,
        edge_own_bonus=p.edge_own_bonus,
        edge_reinforce_factor=p.edge_reinforce_factor,
        enemy_lv1_bonus=p.enemy_lv1_bonus,
        empty_adj_penalty=p.empty_adj_penalty,
        enemy_adj_penalty=p.enemy_adj_penalty,
        low_value_bonus=p.low_value_bonus,
        move_enemy_adj_penalty=p.move_enemy_adj_penalty,
        move_empty_adj_penalty=p.move_empty_adj_penalty,
        onevone_attack_bonus=p.onevone_attack_bonus,
        onevone_attack_lv1_bonus=p.onevone_attack_lv1_bonus,
        onevone_approach_bonus=p.onevone_approach_bonus,
        onevone_frontier_bonus=p.onevone_frontier_bonus,
    )
    entries = ",\n".join([f"  {{{entry}}}"] * 9)
    template = """#pragma once

// Auto-generated by optuna_tune.py

struct Params {{
  int beam_width;
  int max_depth;
  int max_branch;
  double time_limit_ms;
  double alpha;
  double beta;
  double gamma;
  double edge_own_bonus;
  double edge_reinforce_factor;
  double enemy_lv1_bonus;
  double empty_adj_penalty;
  double enemy_adj_penalty;
  double low_value_bonus;
  double move_enemy_adj_penalty;
  double move_empty_adj_penalty;
  double onevone_attack_bonus;
  double onevone_attack_lv1_bonus;
  double onevone_approach_bonus;
  double onevone_frontier_bonus;
}};

static constexpr Params PARAMS_BY_M[9] = {{
{entries}
}};

inline const Params& params_for_m(int m) {{
  if(m < 0) m = 0;
  if(m > 8) m = 8;
  return PARAMS_BY_M[m];
}}
"""
    content = template.format(entries=entries)
    with open(PARAMS_PATH, "w", encoding="utf-8") as f:
        f.write(content)


def run_pahcer(cmd: str, timeout_sec: int) -> float:
    proc = subprocess.run(
        cmd,
        cwd=ROOT_DIR,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=timeout_sec,
        text=True,
    )
    out = proc.stdout
    if proc.returncode != 0:
        print(out)
        raise RuntimeError(f"pahcer failed (exit={proc.returncode})")

    m = REL_SCORE_RE.search(out) or REL_ALT_RE.search(out)
    if not m:
        print(out)
        raise RuntimeError("Relative score not found in output")
    return float(m.group(1))


def objective(trial: optuna.Trial, pahcer_cmd: str, timeout_sec: int) -> float:
    params = TrialParams(
        beam_width=trial.suggest_int("beam_width", 40, 160),
        max_depth=trial.suggest_int("max_depth", 6, 12),
        max_branch=trial.suggest_int("max_branch", 15, 40),
        time_limit_ms=5000.0,
        alpha=trial.suggest_float("alpha", 0.5, 1.5),
        beta=trial.suggest_float("beta", 0.5, 1.5),
        gamma=trial.suggest_float("gamma", 0.0, 0.05),
        edge_own_bonus=trial.suggest_float("edge_own_bonus", 0.0, 0.3),
        edge_reinforce_factor=trial.suggest_float("edge_reinforce_factor", 0.2, 1.0),
        enemy_lv1_bonus=trial.suggest_float("enemy_lv1_bonus", 0.0, 2.0),
        empty_adj_penalty=trial.suggest_float("empty_adj_penalty", 0.0, 0.005),
        enemy_adj_penalty=trial.suggest_float("enemy_adj_penalty", 0.0, 0.01),
        low_value_bonus=trial.suggest_float("low_value_bonus", 0.0, 0.005),
        move_enemy_adj_penalty=trial.suggest_float("move_enemy_adj_penalty", 0.0, 1.0),
        move_empty_adj_penalty=trial.suggest_float("move_empty_adj_penalty", 0.0, 0.4),
        onevone_attack_bonus=0.800000,
        onevone_attack_lv1_bonus=0.800000,
        onevone_approach_bonus=0.300000,
        onevone_frontier_bonus=0.003000,
    )
    write_params(params)
    score = run_pahcer(pahcer_cmd, timeout_sec)
    return score


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--trials", type=int, default=50)
    parser.add_argument("--timeout", type=int, default=600)
    parser.add_argument(
        "--pahcer-cmd",
        default="pahcer run --freeze-best-scores",
    )
    parser.add_argument("--storage", default="sqlite:///optuna/optuna.db")
    parser.add_argument("--study-name", default="ahc061")
    args = parser.parse_args()

    study = optuna.create_study(
        study_name=args.study_name,
        storage=args.storage,
        direction="maximize",
        load_if_exists=True,
    )

    study.optimize(
        lambda t: objective(t, args.pahcer_cmd, args.timeout),
        n_trials=args.trials,
    )

    best = study.best_trial
    print("Best score:", best.value)
    print("Best params:")
    for k, v in best.params.items():
        print(" ", k, v)

    best_params = TrialParams(
        beam_width=int(best.params["beam_width"]),
        max_depth=int(best.params["max_depth"]),
        max_branch=int(best.params["max_branch"]),
        time_limit_ms=5000.0,
        alpha=float(best.params["alpha"]),
        beta=float(best.params["beta"]),
        gamma=float(best.params["gamma"]),
        edge_own_bonus=float(best.params["edge_own_bonus"]),
        edge_reinforce_factor=float(best.params["edge_reinforce_factor"]),
        enemy_lv1_bonus=float(best.params["enemy_lv1_bonus"]),
        empty_adj_penalty=float(best.params["empty_adj_penalty"]),
        enemy_adj_penalty=float(best.params["enemy_adj_penalty"]),
        low_value_bonus=float(best.params["low_value_bonus"]),
        move_enemy_adj_penalty=float(best.params["move_enemy_adj_penalty"]),
        move_empty_adj_penalty=float(best.params["move_empty_adj_penalty"]),
        onevone_attack_bonus=0.800000,
        onevone_attack_lv1_bonus=0.800000,
        onevone_approach_bonus=0.300000,
        onevone_frontier_bonus=0.003000,
    )
    write_params(best_params)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
