#pragma once

// Auto-generated by optuna_tune.py

struct Params {
  int cap_hi;
  int cap_lo;
  int beam_depth;
  int beam_width;
  int rollout_horizon;
  double self_random_eps;
  double eval_potential_w;
  double softmax_temp;
  double ucb_c;
  double eval_reinforce_w;
  double eval_capture_w;
  double eval_piece_pos_w;
  double eval_threat_temp;
};

static constexpr Params PARAMS_BY_M[9] = {
  {-1, -1, -1,   -1, -1, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0},
  {-1, -1, -1,   -1, -1, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0},
  {50, 50, 10,  100, -1, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0},
  {20,  9, -1,   -1, 15, 0.15, 0.10, 0.50, 0.65,  0.5,  0.7, 0.15, 500.0},
  {20,  9, -1,   -1, 15, 0.15, 0.10, 0.50, 0.65,  0.5,  0.7, 0.15, 500.0},
  {20,  9, -1,   -1, 15, 0.15, 0.10, 0.50, 0.65,  0.5,  0.7, 0.15, 500.0},
  {20,  9, -1,   -1, 15, 0.15, 0.10, 0.50, 0.65,  0.5,  0.7, 0.15, 500.0},
  {20,  9, -1,   -1, 15, 0.15, 0.10, 0.50, 0.65,  0.5,  0.7, 0.15, 500.0},
  {20,  9, -1,   -1, 15, 0.15, 0.10, 0.50, 0.65,  0.5,  0.7, 0.15, 500.0}
};

inline const Params& params_for_m(int m) {
  if(m < 0) m = 0;
  if(m > 8) m = 8;
  return PARAMS_BY_M[m];
}
