#pragma once

// Auto-generated by optuna_tune.py

struct Params {
  int max_branch;
  int rollout_horizon;
  double self_random_eps;
  double time_limit_ms;
  double eval_potential_w;
  double softmax_temp;
  double ucb_c;
};

static constexpr Params PARAMS_BY_M[9] = {
  {200, 10, 0.15, 1900.000000, 0.10, 0.50, 0.65},
  {200, 10, 0.15, 1900.000000, 0.10, 0.50, 0.65},
  {200, 10, 0.15, 1900.000000, 0.10, 0.50, 0.65},
  {200, 10, 0.15, 1900.000000, 0.10, 0.50, 0.65},
  {200, 10, 0.15, 1900.000000, 0.10, 0.50, 0.65},
  {200, 10, 0.15, 1900.000000, 0.10, 0.50, 0.65},
  {200, 10, 0.15, 1900.000000, 0.10, 0.50, 0.65},
  {200, 10, 0.15, 1900.000000, 0.10, 0.50, 0.65},
  {200, 10, 0.15, 1900.000000, 0.10, 0.50, 0.65}
};

inline const Params& params_for_m(int m) {
  if(m < 0) m = 0;
  if(m > 8) m = 8;
  return PARAMS_BY_M[m];
}
