#pragma once

// Auto-generated by optuna_tune.py

struct Params {
  int max_branch;
  int rollout_horizon;
  double self_random_eps;
  double time_limit_ms;
};

static constexpr Params PARAMS_BY_M[9] = {
  {100, 10, 1.0000, 1600.000000},
  {100, 10, 1.0000, 1600.000000},
  {100, 10, 1.0000, 1600.000000},
  {100, 10, 1.0000, 1600.000000},
  {100, 10, 1.0000, 1600.000000},
  {100, 10, 1.0000, 1600.000000},
  {100, 10, 1.0000, 1600.000000},
  {100, 10, 1.0000, 1600.000000},
  {100, 10, 1.0000, 1600.000000}
};

inline const Params& params_for_m(int m) {
  if(m < 0) m = 0;
  if(m > 8) m = 8;
  return PARAMS_BY_M[m];
}
