#!/usr/bin/env python3
import argparse
import os
import queue
import re
import shlex
import shutil
import subprocess
import sys
import threading
import time
from dataclasses import dataclass

import optuna

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PARAMS_PATH = os.path.join(ROOT_DIR, "params.hpp")

REL_SCORE_RE = re.compile(r"Relative\s*Score\s*[:=]\s*([0-9.]+)", re.IGNORECASE)
REL_ALT_RE = re.compile(r"^\s*Relative\s*=\s*([0-9.]+)\s*$", re.IGNORECASE | re.MULTILINE)


@dataclass
class TrialParams:
    cap_hi: int
    cap_lo: int
    beam_depth: int
    beam_width: int
    rollout_horizon: int
    self_random_eps: float
    eval_potential_w: float
    softmax_temp: float
    ucb_c: float


def write_params(p: TrialParams) -> None:
    entry = "{cap_hi}, {cap_lo}, {beam_depth}, {beam_width}, {rollout_horizon}, {self_random_eps:.6f}, {eval_potential_w:.6f}, {softmax_temp:.6f}, {ucb_c:.6f}, {eval_reinforce_w:.6f}, {eval_capture_w:.6f}, {eval_piece_pos_w:.6f}, {eval_threat_temp:.6f}".format(
        cap_hi=p.cap_hi,
        cap_lo=p.cap_lo,
        beam_depth=p.beam_depth,
        beam_width=p.beam_width,
        rollout_horizon=p.rollout_horizon,
        self_random_eps=p.self_random_eps,
        eval_potential_w=p.eval_potential_w,
        softmax_temp=p.softmax_temp,
        ucb_c=p.ucb_c,
        eval_reinforce_w=0.5,
        eval_capture_w=0.7,
        eval_piece_pos_w=0.15,
        eval_threat_temp=500.0,
    )
    entries = ",\n".join([f"  {{{entry}}}"] * 9)
    template = """#pragma once

// Auto-generated by optuna_tune.py

struct Params {{
  int cap_hi;
  int cap_lo;
  int beam_depth;
  int beam_width;
  int rollout_horizon;
  double self_random_eps;
  double eval_potential_w;
  double softmax_temp;
  double ucb_c;
  double eval_reinforce_w;
  double eval_capture_w;
  double eval_piece_pos_w;
  double eval_threat_temp;
}};

static constexpr Params PARAMS_BY_M[9] = {{
{entries}
}};

inline const Params& params_for_m(int m) {{
  if(m < 0) m = 0;
  if(m > 8) m = 8;
  return PARAMS_BY_M[m];
}}
"""
    content = template.format(entries=entries)
    with open(PARAMS_PATH, "w", encoding="utf-8") as f:
        f.write(content)


def run_pahcer(cmd: str, timeout_sec: int, stream_log: bool) -> float:
    run_argv = shlex.split(cmd)
    if not run_argv:
        raise RuntimeError("empty pahcer command")
    proc = subprocess.Popen(
        run_argv,
        cwd=ROOT_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    if proc.stdout is None:
        raise RuntimeError("failed to capture pahcer stdout")

    q: queue.Queue[str] = queue.Queue()

    def _reader(pipe, qq: queue.Queue[str]) -> None:
        for line in iter(pipe.readline, ""):
            qq.put(line)
        pipe.close()

    t = threading.Thread(target=_reader, args=(proc.stdout, q), daemon=True)
    t.start()

    deadline = time.monotonic() + timeout_sec
    lines: list[str] = []
    while True:
        while True:
            try:
                line = q.get_nowait()
            except queue.Empty:
                break
            if stream_log:
                print(line, end="")
            lines.append(line)

        rc = proc.poll()
        if rc is not None:
            break
        if time.monotonic() > deadline:
            proc.kill()
            while True:
                try:
                    line = q.get_nowait()
                except queue.Empty:
                    break
                if stream_log:
                    print(line, end="")
                lines.append(line)
            raise RuntimeError(f"pahcer timeout after {timeout_sec}s")
        time.sleep(0.05)

    while True:
        try:
            line = q.get_nowait()
        except queue.Empty:
            break
        if stream_log:
            print(line, end="")
        lines.append(line)

    out = "".join(lines)
    if proc.returncode != 0:
        if not stream_log and out:
            print("[pahcer output - error]")
            print(out, end="" if out.endswith("\n") else "\n")
        raise RuntimeError(f"pahcer failed (exit={proc.returncode})")

    m = REL_SCORE_RE.search(out) or REL_ALT_RE.search(out)
    if not m:
        if out:
            print("[pahcer output - parse failed]")
            print(out, end="" if out.endswith("\n") else "\n")
        raise RuntimeError("Relative score not found in output")
    return float(m.group(1))


def objective(trial: optuna.Trial, pahcer_cmd: str, timeout_sec: int, stream_pahcer_log: bool) -> float:
    cap_hi = trial.suggest_int("cap_hi", 12, 32)
    params = TrialParams(
        cap_hi=cap_hi,
        cap_lo=trial.suggest_int("cap_lo", 4, cap_hi),
        beam_depth=trial.suggest_int("beam_depth", 8, 15),
        beam_width=trial.suggest_int("beam_width", 12, 64),
        rollout_horizon=trial.suggest_int("rollout_horizon", 10, 28),
        self_random_eps=trial.suggest_float("self_random_eps", 0.0, 0.35),
        eval_potential_w=trial.suggest_float("eval_potential_w", 0.0, 2.0),
        softmax_temp=trial.suggest_float("softmax_temp", 0.05, 1.5, log=True),
        ucb_c=trial.suggest_float("ucb_c", 0.0, 2.0),
    )
    print(
        f"[trial {trial.number}] start: "
        f"cap_hi={params.cap_hi}, "
        f"cap_lo={params.cap_lo}, "
        f"beam_depth={params.beam_depth}, "
        f"beam_width={params.beam_width}, "
        f"rollout_horizon={params.rollout_horizon}, "
        f"self_random_eps={params.self_random_eps:.6f}, "
        f"eval_potential_w={params.eval_potential_w:.6f}, "
        f"softmax_temp={params.softmax_temp:.6f}, "
        f"ucb_c={params.ucb_c:.6f}",
        flush=True,
    )
    write_params(params)
    score = run_pahcer(pahcer_cmd, timeout_sec, stream_pahcer_log)
    print(f"[trial {trial.number}] done: relative_score={score:.6f}", flush=True)
    return score


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--trials", type=int, default=50)
    parser.add_argument("--timeout", type=int, default=600)
    parser.add_argument(
        "--pahcer-cmd",
        default="pahcer run --freeze-best-scores",
    )
    parser.add_argument("--storage", default="sqlite:///optuna/optuna.db")
    parser.add_argument("--study-name", default="ahc061")
    parser.add_argument("--stream-pahcer-log", action="store_true")
    args = parser.parse_args()

    pahcer_resolved = shutil.which("pahcer") or "(not found)"
    print(f"[env] python={sys.executable}", flush=True)
    print(f"[env] pahcer={pahcer_resolved}", flush=True)
    print(f"[env] pahcer_cmd={args.pahcer_cmd}", flush=True)
    print(f"[env] stream_pahcer_log={args.stream_pahcer_log}", flush=True)

    study = optuna.create_study(
        study_name=args.study_name,
        storage=args.storage,
        direction="maximize",
        load_if_exists=True,
    )

    study.optimize(
        lambda t: objective(t, args.pahcer_cmd, args.timeout, args.stream_pahcer_log),
        n_trials=args.trials,
        show_progress_bar=True,
    )

    best = study.best_trial
    print("Best score:", best.value)
    print("Best params:")
    for k, v in best.params.items():
        print(" ", k, v)

    best_params = TrialParams(
        cap_hi=int(best.params.get("cap_hi", 20)),
        cap_lo=int(best.params.get("cap_lo", 9)),
        beam_depth=int(best.params.get("beam_depth", 10)),
        beam_width=int(best.params.get("beam_width", 24)),
        rollout_horizon=int(best.params.get("rollout_horizon", 20)),
        self_random_eps=float(best.params.get("self_random_eps", 0.30)),
        eval_potential_w=float(best.params.get("eval_potential_w", 0.0)),
        softmax_temp=float(best.params.get("softmax_temp", 0.30)),
        ucb_c=float(best.params.get("ucb_c", 1.0)),
    )
    write_params(best_params)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
