[general]
version = "0.3.1"

[problem]
problem_name = "masters2026-qual-b"
objective = "Max"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer/b"

[[test.compile_steps]]
program = "g++"
args = ["-O3", "./src/solve_b.cpp", "-o", "./solve_b"]

[[test.compile_steps]]
program = "cargo"
args = ["build", "--release", "--bin", "score"]
current_dir = "../tools"

[[test.compile_steps]]
program = "rm"
args = ["-f", "./score"]

[[test.compile_steps]]
program = "mv"
args = ["../tools/target/release/score", "./score"]

[[test.test_steps]]
program = "./solve_b"
args = []
stdin = "../tools/inB/{SEED04}.txt"
stdout = "../tools/outB/{SEED04}.txt"
stderr = "../tools/errB/{SEED04}.txt"
measure_time = true

[[test.test_steps]]
program = "./score"
args = ["../tools/inB/{SEED04}.txt", "../tools/outB/{SEED04}.txt"]
measure_time = false
