[general]
version = "0.3.1"

[problem]
problem_name = "masters2026-qual-a"
objective = "Max"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer/a"

[[test.compile_steps]]
program = "g++"
args = ["-O3", "./src/solve_a.cpp", "-o", "./solve_a"]

[[test.compile_steps]]
program = "cargo"
args = ["build", "--release", "--bin", "score"]
current_dir = "../tools"

[[test.compile_steps]]
program = "rm"
args = ["-f", "./score"]

[[test.compile_steps]]
program = "mv"
args = ["../tools/target/release/score", "./score"]

[[test.test_steps]]
program = "./solve_a"
args = []
stdin = "../tools/inA/{SEED04}.txt"
stdout = "../tools/outA/{SEED04}.txt"
stderr = "../tools/errA/{SEED04}.txt"
measure_time = true

[[test.test_steps]]
program = "./score"
args = ["../tools/inA/{SEED04}.txt", "../tools/outA/{SEED04}.txt"]
measure_time = false
